POST http://localhost:3003/api/blogs
Content-Type: application/json

{
    "author": "abdulwahab abbas",
    "title": "The progressive growth of generative AI",
    "url": "www.welcometohome.com",
    "likes": 6,
    "userId": "680419edb370ad60fa813569"
}

########
GET http://localhost:3003/api/blogs

#####
DELETE http://localhost:3003/api/blogs